# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('repo', models.CharField(max_length=100)),
                ('demo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('level', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('s_type', models.CharField(choices=[('SL', 'Skill'), ('FM', 'Framework')], max_length=2)),
            ],
        ),
    ]
