# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
