# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_app_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='demo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='repo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
